name: Create Release

on:
  push:
    branches:
      - main
      - packages_setup
    # tags:
    #   - 'v*'  # Trigger on tags that start with 'v', e.g., v0.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install project dependencies
      run: |
        poetry install --no-root

    - name: Build the package
      run: |
        poetry build

    - name: Generate a tag for the release
      run: |
        # Extract version from pyproject.toml using python's toml module
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
        git tag "v$VERSION"
        git push origin "v$VERSION"

    - name: Create GitHub release and upload package
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
