name: Publish Python Package to GitHub Packages

on:
  push:
    # paths:
    #   - 'karya/**'
    branches:
      - main
      - packages_setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install project dependencies
      run: |
        poetry install
        poetry install

    - name: Build the package
      run: |
        poetry build

    - name: Configure to push to Github Packages
      run: |
        poetry config repositories.github https://maven.pkg.github.com/Saumya-Bhatt/karya-python-client

    - name: Publish to GitHub Packages
      run: |
        poetry publish --build --repository github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
