name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'karya/**'
      - 'samples/**'
      - 'source/**'

permissions:
  contents: write

jobs:
  deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install project dependencies
      run: |
        poetry install

    - name: Build the documentation
      run: |
        poetry run sphinx-build source build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
        publish_branch: gh-pages